# Generated by Django 5.2.7 on 2025-11-04 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='normal_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='enter your username', max_length=250)),
                ('email_address', models.EmailField(help_text='enter your email', max_length=250)),
                ('phone_number', models.IntegerField()),
                ('profile_picture', models.ImageField(max_length=250, upload_to='profile_picture')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='enter yout product name', max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='product_image')),
                ('product_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vendor_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cac_image', models.ImageField(upload_to='cac_document')),
                ('nin_image', models.ImageField(upload_to='nin_document')),
                ('user_profile_pic', models.ImageField(upload_to='user_profile_document')),
                ('full_name', models.CharField(max_length=250)),
                ('business_name', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=128)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
