# Generated by Django 5.2.7 on 2025-11-04 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_vendor_admin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_admin',
            name='password',
        ),
    ]
